name: Python CI

# trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubunty-latest

    steps:
      # step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # step 2: set up python environment
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # step 3: install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      # step 4: run tests
      - name: Run tests
        run: pytest


